name = "The Finest Creations"
author = "Treeway7"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b675f6fea8ada9823da289a8e0cff14a27f1f602098fd1ee1e9b4f4ffe963373"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
