name = "The Finest Creations"
author = "Treeway7"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6e3ba4bd7b4cb5381afe02667f34003ac1d66ba185ff27204c85b5e26bce8f7"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
