name = "The Finest Creations"
author = "Treeway7"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5d25095ff3a6ccd94ea3ffb87c9a81cb4fe87afcec6921cf642b83cb436b8ec"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
