name = "The Finest Creations"
author = "Treeway7"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10fe850d003937f48381b8cc74a8beede9a5e5facc19f933514a76251346e016"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
