name = "The Finest Creations"
author = "Treeway7"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a356218a9d8606e8f71bc082230d4614791a1832d5e79c05abc4a753967dace"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
datapack-folder = "global_packs/required_data"
