name = "The Finest Creations"
author = "Treeway7"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af808a941cb5e6104f64f48e778da1ccbbc49af5e07e2d954aab4578725e9f04"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
datapack-folder = "global_packs/required_data"
