name = "The Finest Creations"
author = "Treeway7"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65a9ddd9085bb85bc91d11c4b1f05b5e594f543206046da9bb5f8628886b5432"

[versions]
minecraft = "1.20.1"
quilt = "0.20.2"

[options]
datapack-folder = "global_packs/required_data"
