name = "The Finest Creations"
author = "Treeway7"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "968fe82d6e610846a86ff28fe268b702390c257c3b84679eb395fdfce86c0d03"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"

[options]
datapack-folder = "global_packs/required_data"
